ALTER TABLE  users
    ADD COLUMN  password VARCHAR(255) NOT NULL;

ALTER TABLE users
    ADD COLUMN role VARCHAR(30) NOT NULL;

ALTER TABLE users
    ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users
    ADD COLUMN phone VARCHAR(15) UNIQUE;

ALTER TABLE users
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE users
ALTER COLUMN email TYPE VARCHAR(255);