spring.application.name=ticket-wave
spring.profiles.active=local
server.port=8081
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
security.jwt.secret=Kx4F7pbI7SRzigOCHs2bWTTz39SIvlQZGWvBSyhAaelDImRd9uhFhJCPwtmbshd1dPt2YKtrir/zZ0n8SD+9vA==
security.jwt.expiration=3600000
security.jwt.refresh.expiration=604800000

storage.bucket=ticketwave-images

storage.endpoint=http://localhost:4566

storage.regin=us-east-1